apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-elastic
  labels:
    app: prometheus-elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-elastic
  template:
    metadata:
      labels:
        app: prometheus-elastic
    spec:
      serviceAccountName: elastic-sa
      containers:
        - name: prometheus-elastic
          image: registry.cnbita.com:5000/wuyiqiang/elastic:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-elastic-svc
  labels:
    app: prometheus-elastic
spec:
  type: NodePort
  selector:
    app: prometheus-elastic
  ports:
    - name: http
      port: 8080
      targetPort: 7777
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elastic-sm 
  namespace: default 
spec:
  endpoints:
  - interval: 5s
    port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: prometheus-elastic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-cr
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-crb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic-cr
subjects:
  - kind: ServiceAccount
    name: elastic-sa
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-sa
  namespace: default